[2025-09-11T04:16:03.183+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-11T04:16:03.214+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_pipeline.spark_job manual__2025-09-11T04:15:51.276024+00:00 [queued]>
[2025-09-11T04:16:03.227+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_pipeline.spark_job manual__2025-09-11T04:15:51.276024+00:00 [queued]>
[2025-09-11T04:16:03.229+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-09-11T04:16:03.577+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2025-09-11 04:15:51.276024+00:00
[2025-09-11T04:16:03.601+0000] {standard_task_runner.py:72} INFO - Started process 290 to run task
[2025-09-11T04:16:03.607+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'realtime_pipeline', 'spark_job', 'manual__2025-09-11T04:15:51.276024+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/realtime_pipeline.py', '--cfg-path', '/tmp/tmpx50fr6cg']
[2025-09-11T04:16:03.610+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask spark_job
[2025-09-11T04:16:03.741+0000] {task_command.py:467} INFO - Running <TaskInstance: realtime_pipeline.spark_job manual__2025-09-11T04:15:51.276024+00:00 [running]> on host b2cc818b2b6b
[2025-09-11T04:16:03.873+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='realtime_pipeline' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T04:15:51.276024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-11T04:15:51.276024+00:00'
[2025-09-11T04:16:03.875+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-11T04:16:03.919+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-09-11T04:16:03.921+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.5.1 --num-executors 1 --executor-cores 1 --executor-memory 1g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/apps/spark_streaming.py
[2025-09-11T04:16:04.456+0000] {spark_submit.py:649} INFO - JAVA_HOME is not set
[2025-09-11T04:16:04.541+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.5.1 --num-executors 1 --executor-cores 1 --executor-memory 1g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/apps/spark_streaming.py. Error code is: 1.
[2025-09-11T04:16:04.590+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=realtime_pipeline, task_id=spark_job, run_id=manual__2025-09-11T04:15:51.276024+00:00, execution_date=20250911T041551, start_date=20250911T041603, end_date=20250911T041604
[2025-09-11T04:16:04.655+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-11T04:16:04.657+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task spark_job (Cannot execute: spark-submit --master yarn --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.5.1 --num-executors 1 --executor-cores 1 --executor-memory 1g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/apps/spark_streaming.py. Error code is: 1.; 290)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.5.1 --num-executors 1 --executor-cores 1 --executor-memory 1g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/apps/spark_streaming.py. Error code is: 1.
[2025-09-11T04:16:04.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-11T04:16:04.739+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-11T04:16:04.747+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
